import React from 'react';
import { Card, Typography, Box, Link } from '@mui/material';

import Breadcrumb from '../../../layouts/full-layout/breadcrumb/Breadcrumb';
import PageContainer from '../../../components/container/PageContainer';

const BCrumb = [
  {
    to: '/',
    title: 'Home',
  },
  {
    title: 'Policy',
  },
  {
    title: 'Terms & Condition',
  },
];

const TermsCondition = () => {
  return (
    <PageContainer title="Dream Hunters | Terms & Condition" description="This is Terms & Condition of Dream Hunters">
      {/* breadcrumb */}
      <Breadcrumb title="Terms & Condition" items={BCrumb} />
      {/* end breadcrumb */}
      <Card>
        <Box>
          <Typography variant="h3" component="h1" mt={3}>
            Terms & Condition Cristiano Collection
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            Without prejudice to the continued observance of these <a href="/terms-and-condition" style={{ color: "#216bd6" }}> Terms & Condition </a>
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            Cristiano Collection is a collection of digital artwork (NFT) running on the Ethereum network. This website is just an interface that allows attendees to exchange digital collectibles. Users are entirely responsible for the security and management of their private Ethereum wallets and for validating all transactions and contracts generated by this website prior to approval.<br />
            The NFTs of the Cristiano collection are of 3 types and are assigned to buyers randomly.
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            - Dream Card: 1 total supplied<br />
            - Access Card: 100 total provided<br />
            - Wish Collection: total supply 9,900<br />
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            The rolling royalties deriving from the transactions of the NFTs of the Cristiano collection amount to 15% of the value and will be divided as follows:
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            - 85% owner<br />
            - 4% Cristiano &apos;Wallet<br />
            - 6% owners of the NFTs of the Cristiano collection<br />
            - 1% Dream Hunters Project<br />
            -1% DYInamo Ltd.<br />
            - 3% DAO Christian<br />
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            A. The NFTs belonging to the Cristiano Collection guarantee the following rights to the owner of the NFT:
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            1) Right to vote of the DAO of CRISTIANO<br />
            2) Participation in the random select: once a year Cristiano, through the Dream Hunter app, will assign a random prize to one or more owners of an NFT from his collection (by way of example: a t-shirt or an experience).<br />
            3) Rolling Royalties on the sale of the NFTs of the Cristiano collection according to the following criteria:<br />
            Dream Card 1%<br />
            Access Card 2%<br />
            Wish Collection 3%<br />
            4) Inclusion in the white list of all the collections that Dream Hunters will launch.<br />
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            B. DYInamo Ltd grants you an exempt worldwide license to use, copy, sell, display and display the purchased Art, along with any extension you choose to create or use
          </Typography>

          <Typography variant="body1" color="textSecondary" mt={2}>
            C. For the sake of clarity, nothing in this Section will be deemed to restrict you from owning or operating a market that permits the use and sale of NFTs of the Cristiano Collection in general, provided that the market cryptographically verifies the rights of each owner can demonstrate cryptographically the rights to be the owner of an NFT of Cristiano&apos;s collection.
          </Typography>
        </Box>
      </Card>
    </PageContainer>
  );
};

export default TermsCondition;
