import React from 'react';
import { Card, Typography, Box } from '@mui/material';

import Breadcrumb from '../../layouts/full-layout/breadcrumb/Breadcrumb';
import PageContainer from '../../components/container/PageContainer';

const BCrumb = [
  {
    to: '/',
    title: 'Home',
  },
  {
    title: 'Policy',
  },
  {
    title: 'Terms & Condition',
  },
];

const TermsCondition = () => {
  return (
    <PageContainer title="Dream Hunters | Terms & Condition" description="This is Terms & Condition of Dream Hunters">
      {/* breadcrumb */}
      <Breadcrumb title="Terms & Condition" items={BCrumb} />
      {/* end breadcrumb */}
      <Card>
        <Box>
          <Typography variant="body1" color="textSecondary">
            Dream Hunters is project that produces collections of digital works of art (NFT) running on the Ethereum network owned by DYInamo Ltd .. This website is only an interface that allows participants to purchase digital collectibles. Users are entirely responsible for the security and management of their private Ethereum wallets and for validating all transactions and contracts generated by this website prior to approval. Also, since the smart contract runs on the Ethereum network, it is not possible to reverse, undo or redo any transactions.
            This website and related services are provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. By using this website, you accept sole responsibility for all transactions involving Dream Hunters&apos; digital collectibles.
          </Typography>
        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">1. Ownership</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            1.1 When you purchase an NFT, you fully own the underlying artwork. The ownership of the NFT is entirely mediated by the Smart Contract and the Ethereum Network: at no time can we seize, freeze or otherwise change the ownership of any NFT.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            1.2 Subject to continued compliance with these Terms, DIYnamo Ltd grants you a royalty-free worldwide license to use, copy and display the purchased Art which you may use, solely for the following purposes: a) for personal and non-commercial use; b) as part of a market that allows the purchase, display and sale of your NFT; (c) as part of a third party website or application that allows for the inclusion, engagement or participation of your NFT.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            1.3 In addition to the rights in the Art, nothing in this document confers on the user any rights in other trademarks or other intellectual property rights belonging to DYInamo Ltd including, without limitation, all Dream Hunters products and associated logos. All these rights are expressly reserved in the name of DYInamo Ltd.
          </Typography>
        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">2. Obligations</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            The user is solely responsible for his own conduct while accessing or using the Site and the related consequences. You agree to use the Site only for purposes that are lawful, appropriate and in accordance with these Terms and any applicable laws or regulations. By way of non-limiting example, you cannot and cannot allow third parties to: (i) post, upload, distribute or disseminate any illegal, defamatory, harassing, offensive, fraudulent, hateful, violent, obscene or other objectionable content; (ii) distribute viruses, worms, defects, Trojans, corrupted files, hoaxes or any other element of a destructive or deceptive nature; (iii) impersonate another person; (iv) upload, publish, transmit or otherwise make available through the Site any content that infringes the intellectual property or proprietary rights of any party or otherwise violates the legal rights of others; (v) engage, promote or encourage illegal activities (including, without limitation, money laundering); (vi) interfere with the use of the Site by other users; (vii) use the Site for any unauthorized commercial purpose; (viii) modify, adapt, translate or reverse engineer any part of the Site; (ix) remove any copyright, trademark or other proprietary rights notices contained in or on the Site or any part thereof; (x) use any technology to collect information on the Site for any unauthorized purpose; (xi) access or use the Site for the purpose of creating a competitive product or service with any of our products or services.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">3. Commissions and Payment</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            3.1 If you decide to purchase an NFT through the Site, all financial transactions you engage in will be conducted exclusively through the Ethereum network. We will have no insight or control over these payments or transactions, nor will we have the ability to cancel any transactions. We will have no liability to you or any third party for any claims or damages that may arise as a result of any transaction you undertake or any other transaction you conduct via the Ethereum network.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            3.2 Ethereum requires the payment of a transaction fee (a &quot;Gas Commission&quot;) for each transaction that takes place on the Ethereum network. The Gas Fee funds the computer network that runs Ethereum&apos;s decentralized network. This means that you will have to pay a Gas Commission for each transaction
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">4. Disclaimer</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            4.1 YOU EXPRESSLY UNDERSTAND AND AGREE THAT ACCESS AND USE OF THE SITE IS AT YOUR SOLE RISK AND THAT THE SITE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE MAKE NO EXPRESS WARRANTIES AND WE HEREBY DISCLAIM ALL IMPLIED WARRANTIES REGARDING THE SITE AND ANY PORTION OF IT (INCLUDING, BUT NOT LIMITED TO, THE SITE, ANY WEB SITE OR ANY EXPRESS WEB THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, CORRECTNESS, ACCURACY OR RELIABILITY. WITHOUT LIMITING THE GENERAL FOR THE FOREGOING, WE, OUR SUBSIDIARIES, AFFILIATES AND LICENSORS DO NOT REPRESENT OR WARRANT THAT: (I) YOUR ACCESS TO OR USE OF THE SITE MEETS YOUR REQUIREMENTS, (II) YOUR ACCESS TO OR USE OF THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, (III) THE USE DATA PROVIDED THROUGH THE SITE WILL BE ACCURATE, (III) THE SITE OR ANY CONTENT, SERVICES OR FUNCTIONALITY MADE AVAILABLE ON OR THROUGH THE SITE FROM VIRUSES OR OTHER HARMFUL COMPONENTS, OR (IV) THAT ALL DATA YOU DISCLOSE WHILE USING THE SITE WILL BE SECURE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. OR (IV) THAT ALL DATA YOU DISCLOSE WHEN USING THE SITE WILL BE SECURE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. OR (IV) THAT ALL DATA YOU DISCLOSE WHEN USING THE SITE WILL BE SECURE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            4.2 YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND TRADE ONLINE VIA THE INTERNET AND AGREE THAT WE HAVE NO LIABILITY FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR WILL.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            4.3 WE ARE NOT LIABLE NOR LIABLE TO YOU FOR ANY LOSS FROM WHICH YOU SUFFER AS A RESULT OF THE USE OF THE ETHEREUM NETWORK, NOR WE HAVE NO CONTROL AND NO WARRANTY WITH RESPECT TO ANY INTELLIGENT CONTRACT.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">5. Limitation of Liability</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            5.1 YOU UNDERSTAND AND AGREE THAT WE ARE NOT LIABLE TO YOU OR THIRD PARTIES FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES THAT YOU MAY SUFFER, IN ANY CAUSE AND UNDER ANY THEORY OF LIABILITY, INCLUDING EXAMPLE, ANY LOSS OF PROFITS (FOLLOWED DIRECTLY OR INDIRECTLY), LOSS OF GOODWILL OR COMPANY REPUTATION, LOSS OF DATA, COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR ANY OTHER LOSS OF INTANGIBLE DAMAGES POSSIBLE.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            5.2 YOU AGREE THAT OUR TOTAL AND AGGREGATE LIABILITY TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR ACCESS OR USE (OR IMPOSSIBILITY TO ACCESS OR USE) ANY PART OF THE THE SITE, WHETHER IN CONTRACT, TORT, STRICT LIABILITY OR ANY OTHER LEGAL THEORY, IS LIMITED TO THE GREATER (A) OF THE AMOUNTS ACTUALLY PAID UNDER THESE TERMS FOR THE PERIOD OF 12 MONTHS BEFORE THE DATE ON WHICH THE CLAIM IS SENT.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            5.3 YOU ACKNOWLEDGE AND AGREE THAT WE HAVE MADE THE SITE AVAILABLE AND ENTERED THESE CONDITIONS UNDER THE WARRANTY EXCLUSIONS AND LIMITATIONS OF LIABILITY SET FORTH HEREIN. WE WILL NOT BE ABLE TO PROVIDE THE SITE WITHOUT THESE LIMITATIONS.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">6. Assumption of risk</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            6.1 To the extent that you sell your NFT, please note that NFT prices are extremely volatile and the price fluctuations of other NFTs and affect the price of your NFT both positively and negatively. Given the volatility, NFTs should not be considered an investment. You take all the risks in this regard.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            6.2 The ownership of an NFT of the Dream Hunters collections confers ownership of the digital artwork only. Consequently, no information on this Site (or any other document mentioned therein) is or can be considered advice or an invitation to enter into an agreement for any investment purpose. Further, nothing on this Site qualifies or is intended as an offer of securities in any jurisdiction nor does it constitute an offer or invitation to purchase any stock, security or other financial product. Due to the artistic nature of the project.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            6.3 You assume all risks associated with the use of an Internet-based currency, including but not limited to the risk of hardware, software and Internet connections, the risk of introducing malicious software, and the risk that third parties may gain unauthorized access to information stored in your wallet.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            6.4 NFTs, cryptocurrencies and blockchain technology are relatively new and the regulatory landscape is unstable. The new regulations could negatively impact such technologies affecting the value of your NFT. You understand and accept all the risks involved.
          </Typography>
          <Typography variant="body1" color="textSecondary" mt={1}>
            6.5 You assume all responsibility for any adverse effects of disruptions or other issues affecting Ethereum or the Ethereum platform.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">7. Indemnification</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            You agree to indemnify and indemnify DYInamo Ltd and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensees, suppliers or partners from and against any claim, liability, loss, damage (real and consequential) of any kind or nature, lawsuit, judgment, litigation costs and reasonable attorney&apos;s fees arising out of or in any way related to (i) your breach of these Terms, (ii) your misuse of the Site, or (iii) your breach of any laws, rules or regulations in relation to your access or use of the Site.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">8. Changes to the Terms and Conditions</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            We may make changes to the Terms at our discretion. Please check these Terms periodically for any changes. Any changes to the Terms will apply on the date they are made and your continued access or use after updating the Terms will constitute your binding acceptance of the updates. If you do not accept the modified Terms, you cannot access or use the Site.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">9. Children</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            Our site is not intended for children. You must be at least 18 years old to access this site or purchase an NFT. If you are under the age of 18 you are not authorized to use this Site for any reason. By accessing the Site, you represent and warrant that you are at least 18 years of age.
          </Typography>

        </Box>
      </Card>
      <Card>
        <Box>
          <Typography variant="h3">10. Governing Law & Jurisdiction</Typography>

          <Typography variant="body1" color="textSecondary" mt={1}>
            These Terms will be governed by and interpreted in accordance with the laws of the UK, and you submit to the non-exclusive jurisdiction of the UK and those courts located herein for the resolution of any disputes.
          </Typography>

        </Box>
      </Card>
    </PageContainer>
  );
};

export default TermsCondition;
